---
title: "Time_Series_Assignment_2"
output: html_document
date: "2025-04-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Loading libraries
suppressPackageStartupMessages({
  suppressWarnings({
    library(tidyverse)
    library(lubridate)
    library(TSA)
    library(tseries)
    library(zoo)
    library(lmtest)
    library(forecast)
    library(fUnitRoots)
  })
})
```

```{r}
# Loading the dataset
data <- read.csv("assignment2Data2025.csv")
```

```{r}
# Checking Column Names in the dataset
colnames(data)
# Checking the class
class(data)
class(data$Date)
class(data$Bitcoin)
# Check for missing values
colSums(is.na(data))
#Checking Summary
summary(data)
```

```{r}
# Creating time series object
btc_ts <- ts(data$Bitcoin, start = c(2011, 8), frequency = 12)
```


```{r}
plot(btc_ts,
     type = "o",
     main = "Figure 1: Bitcoin Index (USD) from Aug 2011 to Jan 2025",
     xlab = "Year",
     ylab = "Bitcoin Index (USD)")
```

```{r}
# Assigning Bitcoin column to y
y <- data$Bitcoin

x1 <- zlag(data$Bitcoin)
index1 <- 2:length(x1)

# Correlation at lag 1
cor(y[index1], x1[index1])

# Plotting lag 1
plot(y[index1], x1[index1],
     main = "Figure 2: Lag 1 Scatter Plot",
     xlab = "Lag 1",
     ylab = "Original Bitcoin Data")
```

```{r}
# ----- Lag 2 -----
x2 <- zlag(zlag(data$Bitcoin))
index2 <- 3:length(x2)

# Correlation at lag 2
cor(y[index2], x2[index2])

# Plotting lag 2
plot(y[index2], x2[index2],
     main = "Figure 3: Lag 2 Scatter Plot",
     xlab = "Lag 2",
     ylab = "Original Bitcoin Data")
```

```{r}
# ACF Plot
acf(btc_ts,main = "Figure 4: ACF of Bitcoin Index", lag.max = 60)

# PACF Plot
pacf(btc_ts,main = "Figure 5: PACF of Bitcoin Index")
```

```{r}
adf.test(btc_ts)
pp.test(btc_ts)
kpss.test(btc_ts)
```

```{r}
qqnorm(y=btc_ts, main = "Figure 6: QQ plot of Bitcoin")
qqline(y=btc_ts, col = 2, lwd = 1, lty = 2)
shapiro.test(btc_ts)
```

```{r}
#Log Transformation
btc_tslog <- log(btc_ts)
plot(btc_tslog,
     type = "o",
     main = "Figure 7: Log Transformation Bitcoin Index",
     ylab = "Differenced Bitcoin",
     xlab = "Time")
```

```{r}
qqnorm(y=btc_tslog, main = "Figure 8: QQ plot of Log Transformed Data")
qqline(y=btc_tslog, col = 2, lwd = 1, lty = 2)
shapiro.test(btc_tslog)
```

```{r}
acf(btc_tslog, main ="Figure 9: ACF plot of Log Transformed Data.", lag.max = 60)
pacf(btc_tslog, main ="Figure 10: PACF plot of Log Transformed Data.", lag.max = 60)
```

```{r}
adf.test(btc_tslog)
pp.test(btc_tslog)
kpss.test(btc_tslog)
```

```{r}
#Box-Cox Transformation
BC = BoxCox.ar(btc_ts,lambda = seq(-0.4, 0.5, 0.01))
BC$ci
lambda <- BC$lambda[which(max(BC$loglike) == BC$loglike)]
lambda
BC.data = (btc_ts^lambda-1)/lambda

plot(BC.data,type='o',ylab='BC-transformed', main = " Figure 11: Time series plot of BC-transformed." )
```


```{r}
qqnorm(y=BC.data, main = "Figure 12: BC QQ plot of Bitcoin")
qqline(y=BC.data, col = 2, lwd = 1, lty = 2)
shapiro.test(BC.data)
```

```{r}
acf(BC.data, main ="Figure 13: ACF plot of BC-transformed Data.", lag.max = 60)
pacf(BC.data, main ="Figure 14: PACF plot of BC-transformed Data.", lag.max = 60)
```


```{r}
adf.test(BC.data)
pp.test(BC.data)
kpss.test(BC.data)
```


```{r}
BC.data.diff <- diff(BC.data, differences = 1)
plot(BC.data.diff, type='o',ylab='BC-transformedDiff', main = " Figure 15: Time series plot of BC-transformed Differencing Series.")
```

```{r}
qqnorm(y=BC.data.diff, main = "Figure 16: BC QQ plot of Bitcoin")
qqline(y=BC.data.diff, col = 2, lwd = 1, lty = 2)
shapiro.test(BC.data.diff)
```


```{r}
adf.test(BC.data.diff)
pp.test(BC.data.diff)
kpss.test(BC.data.diff)
```


```{r}
acf(BC.data.diff, main = "Figure 17: ACF of BC Differencing Transformation")
pacf(BC.data.diff, main = "Figure 18: PACF of BC Differencing Transformation")
```

```{r}
eacf(BC.data.diff)
```

```{r}
BC.bic = armasubsets(y= BC.data.diff, nar=5, nma=5, y.name='p', ar.method='ols')
plot(BC.bic)
mtext("Figure 19: BIC of BC Differenced Data", side = 1, line = 1, cex = 1)
```

# Final Set of possible models ARIMA,
#{ARIMA(1,1,1)} {ARIMA(1, 1, 2)} {ARIMA(2, 1, 1)} {ARIMA(2, 1, 2)} {ARIMA(0,1,1)}  {ARIMA(1,1,0)}  {ARIMA(1,1,4)} 


```{r}
# ARIMA(1,1,1)
model.111 = Arima(btc_ts,order=c(1,1,1), method='ML')
coeftest(model.111)

model.111CSS = Arima(btc_ts,order=c(1,1,1), method='CSS')
coeftest(model.111CSS)

model.111CSS_ML = Arima(btc_ts,order=c(1,1,1), method='CSS-ML')
coeftest(model.111CSS_ML)
```

```{r}
#ARIMA(1, 1, 2)
model.112 = Arima(btc_ts,order=c(1,1,2), method='ML')
coeftest(model.112)

model.112CSS = Arima(btc_ts,order=c(1,1,2), method='CSS')
coeftest(model.112CSS)

model.112CSS_ML = Arima(btc_ts,order=c(1,1,2), method='CSS-ML')
coeftest(model.112CSS_ML)
```

```{r}
#ARIMA(2, 1, 1)
model.211 = Arima(btc_ts,order=c(2,1,1), method='ML')
coeftest(model.211)

model.211CSS = Arima(btc_ts,order=c(2,1,1), method='CSS')
coeftest(model.112CSS)

model.211CSS_ML = Arima(btc_ts,order=c(2,1,1), method='CSS-ML')
coeftest(model.211CSS_ML)
```

```{r}
#ARIMA(2, 1, 2)
model.212 = Arima(btc_ts,order=c(2,1,2), method='ML')
coeftest(model.212)

model.212CSS = Arima(btc_ts,order=c(2,1,2), method='CSS')
coeftest(model.212CSS)

model.212CSS_ML = Arima(btc_ts,order=c(2,1,2), method='CSS-ML')
coeftest(model.212CSS_ML)
```


```{r}
#{ARIMA(0,1,1)}
model.011 = Arima(btc_ts,order=c(0,1,1), method='ML')
coeftest(model.011)

model.011CSS = Arima(btc_ts,order=c(0,1,1), method='CSS')
coeftest(model.011CSS)

model.011CSS_ML = Arima(btc_ts,order=c(0,1,1), method='CSS-ML')
coeftest(model.011CSS_ML)

```

```{r}
# {ARIMA(1,1,0)}
model.110 = Arima(btc_ts,order=c(1,1,0), method='ML')
coeftest(model.110)

model.110CSS = Arima(btc_ts,order=c(1,1,0), method='CSS')
coeftest(model.110CSS)

model.110CSS_ML = Arima(btc_ts,order=c(1,1,0), method='CSS-ML')
coeftest(model.110CSS_ML)
```

```{r}
#{ARIMA(1,1,4)}
model.114 = Arima(btc_ts,order=c(1,1,4), method='ML')
coeftest(model.114)

model.114CSS = Arima(btc_ts,order=c(1,1,4), method='CSS')
coeftest(model.114CSS)

model.114CSS_ML = Arima(btc_ts,order=c(1,1,4), method='CSS-ML')
coeftest(model.114CSS_ML)
```

```{r}
sort.score <- function(x, score = c("bic", "aic")){
  if (score == "aic"){
    x[with(x, order(AIC)),]
  } else if (score == "bic") {
    x[with(x, order(BIC)),]
  } else {
    warning('score = "x" only accepts valid arguments ("aic","bic")')
  }
}
```


```{r}
sort.score(AIC(model.111,model.112,model.211,model.212,model.011,model.110,model.114), score = "aic")
```

```{r}
sort.score(BIC(model.111,model.112,model.211,model.212,model.011,model.110,model.114), score = "bic")
```

#{ARIMA(1,1,1)} {ARIMA(1, 1, 2)} {ARIMA(2, 1, 1)} {ARIMA(2, 1, 2)} {ARIMA(0,1,1)}  {ARIMA(1,1,0)}  {ARIMA(1,1,4)}

```{r}
model_111_acc <- accuracy(model.111)[1:7]
model_112_acc <- accuracy(model.112)[1:7]
model_211_acc <- accuracy(model.211)[1:7]
model_212_acc <- accuracy(model.212)[1:7]
model_011_acc <- accuracy(model.011)[1:7]
model_110_acc <- accuracy(model.110)[1:7]
model_114_acc <- accuracy(model.114)[1:7]
df.models <- data.frame(
  rbind(model_111_acc,model_112_acc,model_211_acc,model_212_acc,model_011_acc,model_110_acc,
        model_114_acc)
)
colnames(df.models) <- c("ME", "RMSE", "MAE", "MPE", "MAPE", 
                          "MASE", "ACF1")
rownames(df.models) <- c("ARIMA(1,1,1)", "ARIMA(1, 1, 2)", "ARIMA(2, 1, 1)", "ARIMA(2, 1, 2)", "ARIMA(0,1,1)", "ARIMA(1,1,0)", "ARIMA(1,1,4)")
round(df.models,  digits = 3)
```

```{r}
model.213ml = Arima(btc_ts,order=c(2,1,3),method='ML')
coeftest(model.213ml) 

model.213css = Arima(btc_ts,order=c(2,1,3),method='CSS')
coeftest(model.213css)

model.213mlcss = Arima(btc_ts,order=c(2,1,3),method='CSS-ML')
coeftest(model.213mlcss)

```


```{r}
model.312ml = Arima(btc_ts,order=c(3,1,2),method='ML')
coeftest(model.312ml) 

model.312css = Arima(btc_ts,order=c(3,1,2),method='CSS')
coeftest(model.312css)

model.312mlcss = Arima(btc_ts,order=c(3,1,2),method='CSS-ML')
coeftest(model.312mlcss)

```




