---
title: "TimeSeriesProject"
output: html_document
date: "2025-05-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load necessary libraries
suppressPackageStartupMessages({
  suppressWarnings({
    library(readr)
    library(dplyr)
    library(lubridate)
    library(FitAR)
    library(ggplot2)
    library(forecast)
    library(TSA)
    library(fUnitRoots)
    library(FitAR)
    library(lmtest)
    library(tseries)
  })
})
```

```{r}
# Read the CSV file
df <- read_csv("Yellowstone.csv")
```

```{r}
# Cleanning RecreationVisits column
df <- df %>%
  mutate(RecreationVisits = as.numeric(gsub(",", "", RecreationVisits)),
         Date = make_date(Year, Month, 1)) %>%
  arrange(Date)
```

```{r}
# Creating time series object from January 2000 to December 2024
yellowstone_ts <- ts(df$RecreationVisits, start = c(2000, 1), frequency = 12)
```

```{r}
# Plotting time series
plot(yellowstone_ts, ylab = "Visitors", xlab = "Year", main = "Fig 1: Yellowstone Monthly Visitors (2000–2024)", type = "o")
```

```{r}
# Structure
str(df)

# Summary statistics for RecreationVisits
summary(df$RecreationVisits)

# Missing value check
sum(is.na(df$RecreationVisits))
which(is.na(df$RecreationVisits))  
```

```{r}
# Creating lagged version of the Yellowstone time series
y <- yellowstone_ts
x <- zlag(y)  

index <- 2:length(x)

# Computing lag-1 correlation
correlation_lag1 <- cor(y[index], x[index])
print(paste("Lag 1 Correlation:", round(correlation_lag1, 4)))

# Scatter plot of original vs lagged values
plot(y[index], x[index],
     main = "Fig 2: Lag 1 Scatter Plot",
     xlab = "Lag 1 (Previous Month's Visitors)",
     ylab = "Current Month's Visitors")
```

```{r}
acf(yellowstone_ts, lag.max = 60, main = "Fig 3: ACF plot")
```


```{r}
# Time index
t <- 1:length(yellowstone_ts)

# 1. Linear Model
model1 <- lm(yellowstone_ts ~ t)
summary(model1)

# Fitted values
fitted.model1 <- fitted(model1)

# Plotting 
plot(t, yellowstone_ts, type = 'o', ylab = 'Visitors', 
     main = 'Fig 4: Linear Model Fit', xlab = 'Time (Index)')
lines(t, fitted.model1, col = 'red', lty = 2)

```



```{r}
# Residual Analysis
res.model1 <- rstudent(model1)

par(mfrow = c(2, 2))
plot(res.model1, type = 'l', main = "Fig 4.1: Standardized Residuals")
hist(res.model1, main = "Fig 4.2: Histogram of Residuals")
qqnorm(res.model1, main = "Fig 4.3: QQ Plot of Residuals")
qqline(res.model1, col = 2)
acf(res.model1, main = "Fig 4.4: ACF of Residuals")
par(mfrow = c(1, 1))

# Normality test
shapiro.test(res.model1)
```

```{r}
# Time index
t <- 1:length(yellowstone_ts)
t2 <- t^2

# 2. Quadratic Model
model2 <- lm(yellowstone_ts ~ t + t2)
summary(model2)

# Fitted values
fitted.model2 <- fitted(model2)

# Plot 
plot(t, yellowstone_ts, type = 'o', ylab = 'Visitors', xlab = 'Time Index',
     main = 'Fig 5: Quadratic Model Fit')
lines(t, fitted.model2, col = 'red', lty = 2)

```


```{r}
# Residual Analysis for Quadratic Model
res.model2 <- rstudent(model2)

par(mfrow = c(2, 2))
plot(res.model2, type = 'l', main = "Fig 5.1: Standardized Residuals")
hist(res.model2, main = "Fig 5.2: Histogram of Residuals")
qqnorm(res.model2, main = "Fig 5.3: QQ Plot of Residuals")
qqline(res.model2, col = 2)
acf(res.model2, main = "Fig 5.4: ACF of Residuals")
par(mfrow = c(1, 1))

# Normality test
shapiro.test(res.model2)
```

```{r}
# Cosine Model
t <- 1:length(yellowstone_ts)
cos_term <- cos(2 * pi * t / 12)  
model3 <- lm(yellowstone_ts ~ cos_term)
summary(model3)

# Fitted values and plot
fitted.model3 <- fitted(model3)
plot(t, yellowstone_ts, type = 'o', ylab = 'Visitors', xlab = 'Time Index',
     main = 'Fig 6: Cosine Model Fit')
lines(t, fitted.model3, col = 'red', lty = 2)

```

```{r}
res.model3 <- rstudent(model3)

par(mfrow = c(2, 2))
plot(res.model3, type = 'l', main = "Fig.6.1: Standardized Residuals")
hist(res.model3, main = "Fig.6.2: Histogram of Residuals")
qqnorm(res.model3, main = "Fig.6.3: QQ Plot")
qqline(res.model3, col = 2)
acf(res.model3, main = "Fig.6.4: ACF of Residuals")
par(mfrow = c(1, 1))

shapiro.test(res.model3)

```

```{r}
# Cyclical Model (Cosine + Sine)
sin_term <- sin(2 * pi * t / 12)
model4 <- lm(yellowstone_ts ~ cos_term + sin_term)
summary(model4)
 
# Fitted values and plot
fitted.model4 <- fitted(model4)
plot(t, yellowstone_ts, type = 'o', ylab = 'Visitors', xlab = 'Time Index',
     main = 'Fig 7: Cyclical Model Fit (Cos + Sin)')
lines(t, fitted.model4, col = 'red', lty = 2)
```

```{r}
res.model4 <- rstudent(model4)
 
par(mfrow = c(2, 2))
plot(res.model4, type = 'l', main = "Fig.7.1: Standardized Residuals")
hist(res.model4, main = "Fig.7.2: Histogram of Residuals")
qqnorm(res.model4, main = "Fig.7.3: QQ Plot")
qqline(res.model4, col = 2)
acf(res.model4, main = "Fig.7.4: ACF of Residuals")
par(mfrow = c(1, 1))
 
shapiro.test(res.model4)
```


```{r}
# Creating month factor variable
months <- cycle(yellowstone_ts)
month_factors <- factor(months)

# Seasonal Dummy Model
model5 <- lm(yellowstone_ts ~ month_factors)
summary(model5)

# Fitted values and plot
fitted.model5 <- fitted(model5)
plot(t, yellowstone_ts, type = 'o', ylab = 'Visitors', xlab = 'Time Index',
     main = 'Fig: 8 Seasonal Dummy Variable Model')
lines(t, fitted.model5, col = 'red', lty = 2)

```

```{r}
res.model5 <- rstudent(model5)

par(mfrow = c(2, 2))
plot(res.model5, type = 'l', main = "Fig: 8.1 Standardized Residuals")
hist(res.model5, main = "Fig: 8.2 Histogram of Residuals")
qqnorm(res.model5, main = "Fig: 8.3 QQ Plot")
qqline(res.model5, col = 2)
acf(res.model5, main = "Fig: 8.4 ACF of Residuals")
par(mfrow = c(1, 1))

shapiro.test(res.model5)

```

```{r}
freq <- frequency(yellowstone_ts)
n_future <- 10
t_future <- (length(yellowstone_ts) + 1):(length(yellowstone_ts) + n_future)
future_months <- ((cycle(yellowstone_ts)[length(yellowstone_ts)] + 1:n_future - 1) %% freq) + 1
future_month_factors <- factor(future_months, levels = 1:freq)
new_data <- data.frame(month_factors = future_month_factors)
forecast_values <- predict(model5, newdata = new_data)
 

forecast_tbl <- data.frame(
  Time_Index        = t_future,
  Month             = future_months,
  Forecast_Visitors = round(forecast_values, 0)   
)
 
print(forecast_tbl, row.names = FALSE)
 
plot(t, yellowstone_ts, type = 'o', ylab = 'Visitors', xlab = 'Time Index',
     main = 'Fig 9: Seasonal Dummy Variable Model with Forecast')
lines(t, fitted.model5, col = 'red', lty = 2)
points(t_future, forecast_values, col = 'blue', pch = 19)
lines(t_future, forecast_values, col = 'blue', lty = 2)
legend("topleft",
       legend = c("Actual", "Fitted", "Forecast"),
       col = c("black", "red", "blue"), lty = c(1, 2, 2), pch = c(1, NA, 19))
```



```{r}
residual.analysis <- function(model, std = TRUE,start = 2, class = c("ARIMA","GARCH","ARMA-GARCH", "fGARCH")[1]){
  library(TSA)
  library(FitAR)
  if (class == "ARIMA"){
    if (std == TRUE){
      res.model = rstandard(model)
    }else{
      res.model = residuals(model)
    }
  }else if (class == "GARCH"){
    res.model = model$residuals[start:model$n.used]
  }else if (class == "ARMA-GARCH"){
    res.model = model@fit$residuals
  }else if (class == "fGARCH"){
    res.model = model@residuals
  }else {
    stop("The argument 'class' must be either 'ARIMA' or 'GARCH' ")
  }
  par(mfrow=c(3,2))
  plot(res.model,type='o',ylab='Standardised residuals', main="Time series plot of standardised residuals")
  abline(h=0)
  hist(res.model,main="Histogram of standardised residuals")
  qqnorm(res.model,main="QQ plot of standardised residuals")
  qqline(res.model, col = 2)
  seasonal_acf(res.model,main="ACF of standardised residuals")
  print(shapiro.test(res.model))
  k=0
  LBQPlot(res.model, lag.max = 30, StartLag = k + 1, k = 0, SquaredQ = FALSE)
  par(mfrow=c(1,1))
}
```


```{r}
helper <- function(class = c("acf", "pacf"), ...) {
  
  # Capture additional arguments
  params <- match.call(expand.dots = TRUE)
  params <- as.list(params)[-1]
  
  # Calculate ACF/PACF values
  if (class == "acf") {
    acf_values <- do.call(acf, c(params, list(plot = FALSE)))
  } else if (class == "pacf") {
    acf_values <- do.call(pacf, c(params, list(plot = FALSE)))
  }
  
  # Extract values and lags
  acf_data <- data.frame(
    Lag = as.numeric(acf_values$lag),  
    ACF = as.numeric(acf_values$acf)   
  )
  
  # Identify seasonal lags to be highlighted
  seasonal_lags <- acf_data$Lag %% 1 == 0
  
  # Plot ACF/PACF values
  if (class == "acf") {
    do.call(acf, c(params, list(plot = TRUE)))
  } else if (class == "pacf") {
    do.call(pacf, c(params, list(plot = TRUE)))
  }
  
  # Add colored segments for seasonal lags
  for (i in which(seasonal_lags)) {
    segments(x0 = acf_data$Lag[i], y0 = 0, x1 = acf_data$Lag[i], y1 = acf_data$ACF[i], col = "red")
  }
}

```

```{r}
# seasonal_acf
seasonal_acf <- function(...) {
  helper(class = "acf", ...)
}

# seasonal_pacf
seasonal_pacf <- function(...) {
  helper(class = "pacf", ...)
}
```


```{r}
par(mfrow=c(1,2))
seasonal_acf(yellowstone_ts,  lag.max = 64,main="Fig: 10 Seasonal ACF")
seasonal_pacf(yellowstone_ts,  lag.max = 64,main="Fig: 11 Seasonal PACF")
par(mfrow=c(1,1))
```


```{r}
# Test for stationarity
adf.test(yellowstone_ts)
pp.test(yellowstone_ts)
kpss.test(yellowstone_ts)
shapiro.test(yellowstone_ts)
```

```{r}
yellowstone_ts_adj <- yellowstone_ts
yellowstone_ts_adj[yellowstone_ts_adj <= 0] <- 1

lambda_seq <- seq(0, 2, 0.01)  # or any custom range

# Performing Box-Cox likelihood profile search
BC <- BoxCox.ar(yellowstone_ts_adj, lambda = lambda_seq)

# Extracting optimal lambda
lambda_opt <- BC$lambda[which.max(BC$loglike)]
print(paste("Optimal lambda in range -1 to 1.5:", round(lambda_opt, 3)))
lambda_opt
# Applying Box-Cox transformation with lambda = 0.36
ts_transformed <- BoxCox(yellowstone_ts_adj, lambda = 0.36)

```

```{r}
shapiro.test(ts_transformed)
adf.test(ts_transformed)
pp.test(ts_transformed)
kpss.test(ts_transformed)
```

```{r}
m1 <- Arima(yellowstone_ts, order = c(0, 0, 0), seasonal = list(order = c(0, 1, 0), period = 12))
res1 <- residuals(m1)
par(mfrow=c(1,1))
plot(res1,xlab='Time',ylab='Residuals',main="Fig: 12 Time series plot of the residuals")
par(mfrow=c(1,2))
seasonal_acf(res1, lag.max = 48, main = "Fig: 13 ACF of m1 residuals")
seasonal_pacf(res1, lag.max = 48, main = "Fig: 14 PACF of m1 residuals")
```

```{r}
m2 <- Arima(yellowstone_ts, order = c(0, 0, 0), seasonal = list(order = c(1, 1, 1), period = 12))
res2 <- residuals(m2)
par(mfrow=c(1,1))
plot(res2,xlab='Time',ylab='Residuals',main="Fig: 15 Time series plot of m2 residual")
par(mfrow=c(1,2))
seasonal_acf(res2, lag.max = 48, main = "Fig: 16 ACF of m2 residuals")
seasonal_pacf(res2, lag.max = 48, main = "Fig: 17 PACF of m2 residuals")
```


```{r}
m3 = Arima(yellowstone_ts,order=c(0,1,0),seasonal=list(order=c(1,1,1), period=12))
res3 = residuals(m3);  
par(mfrow=c(1,1))
plot(res3,xlab='Time',ylab='Residuals',main="Fig: 18 Time series plot of m3 residual")
par(mfrow=c(1,2))
seasonal_acf(res3, lag.max = 36, main = "Fig: 19 ACF of m3 residuals")
seasonal_pacf(res3, lag.max = 36, main = "Fig: 20 PACF of m3 residuals")
```

```{r}
m4 = Arima(yellowstone_ts,order=c(5,1,2),seasonal=list(order=c(1,1,1), period=12))
res4 = residuals(m4);  
par(mfrow=c(1,1))
plot(res4,xlab='Time',ylab='Residuals',main="Fig: 21 Time series plot of m4 residual")
par(mfrow=c(1,2))
seasonal_acf(res4, lag.max = 36, main = "Fig: 22 ACF of m4 residuals")
seasonal_pacf(res4, lag.max = 36, main = "Fig: 23 PACF of m4 residuals")
```

```{r}
eacf(res3)
```


```{r}
par(mfrow=c(1,1))
bic_table = armasubsets(y=res3,nar=5,nma=5,y.name='p',ar.method='ols')
plot(bic_table)
mtext("Fig 25: BIC Table", side = 1, line = 1, cex = 1)
```

```{r}
# SARIMA(5,1,2)x(1,1,1)_12
m3_512.bhemanML = Arima(yellowstone_ts,order=c(5,1,2),seasonal=list(order=c(1,1,1), period=12),method = "ML")
coeftest(m3_512.bhemanML)
residual.analysis(model = m3_512.bhemanML)
```

```{r}
m3_512.bhemanCSS = Arima(yellowstone_ts,order=c(5,1,2),seasonal=list(order=c(1,1,1), period=12),method = "CSS")
coeftest(m3_512.bhemanCSS)
residual.analysis(model = m3_512.bhemanCSS)
```

```{r}
m3_512.bhemanCSSML = Arima(yellowstone_ts,order=c(5,1,2),seasonal=list(order=c(1,1,1), period=12),method = "CSS-ML")
coeftest(m3_512.bhemanCSSML)
residual.analysis(model = m3_512.bhemanCSSML)
```

```{r}
# SARIMA(1,1,2)x(1,1,1)_12
m3_112.bhemanML = Arima(yellowstone_ts,order=c(1,1,2),seasonal=list(order=c(1,1,1), period=12),method = "ML")
coeftest(m3_112.bhemanML)
residual.analysis(model = m3_112.bhemanML)
```

```{r}
# SARIMA(2,1,2)x(1,1,1)_12
m3_212.bhemanML = Arima(yellowstone_ts,order=c(2,1,2),seasonal=list(order=c(1,1,1), period=12),method = "ML")
coeftest(m3_212.bhemanML)
residual.analysis(model = m3_212.bhemanML)
```

```{r}
m3_212.bhemanCSS = Arima(yellowstone_ts,order=c(2,1,2),seasonal=list(order=c(1,1,1), period=12),method = "CSS")
coeftest(m3_212.bhemanCSS)
residual.analysis(model = m3_212.bhemanCSS)
```

```{r}
m3_212.bhemanCSSML = Arima(yellowstone_ts,order=c(2,1,2),seasonal=list(order=c(1,1,1), period=12),method = "CSS-ML")
coeftest(m3_212.bhemanCSSML)
residual.analysis(model = m3_212.bhemanCSSML)
```

```{r}
# SARIMA(1,1,3)x(1,1,1)_12
m3_113.bhemanML = Arima(yellowstone_ts,order=c(1,1,3),seasonal=list(order=c(1,1,1), period=12),method = "ML")
coeftest(m3_113.bhemanML)
residual.analysis(model = m3_113.bhemanML)
```

```{r}
m3_113.bhemanCSS = Arima(yellowstone_ts,order=c(1,1,3),seasonal=list(order=c(1,1,1), period=12),method = "CSS")
coeftest(m3_113.bhemanCSS)
residual.analysis(model = m3_113.bhemanCSS)
```

```{r}
# SARIMA(2,1,3)x(1,1,1)_12
m3_213.bhemanML = Arima(yellowstone_ts,order=c(2,1,3),seasonal=list(order=c(1,1,1), period=12),method = "ML")
coeftest(m3_213.bhemanML)
residual.analysis(model = m3_213.bhemanML)
```

```{r}
m3_213.bhemanCSS = Arima(yellowstone_ts,order=c(2,1,3),seasonal=list(order=c(1,1,1), period=12),method = "CSS")
coeftest(m3_213.bhemanCSS)
residual.analysis(model = m3_213.bhemanCSS)
```

```{r}
m3_213.bhemanCSSML = Arima(yellowstone_ts,order=c(2,1,3),seasonal=list(order=c(1,1,1), period=12),method = "CSS-ML")
coeftest(m3_213.bhemanCSSML)
residual.analysis(model = m3_213.bhemanCSSML)
```

```{r}
# SARIMA(1,1,1)x(1,1,1)_12
m3_111.bhemanML = Arima(yellowstone_ts,order=c(1,1,1),seasonal=list(order=c(1,1,1), period=12),method = "ML")
coeftest(m3_111.bhemanML)
residual.analysis(model = m3_111.bhemanML)
```

```{r}
# SARIMA(2,1,1)x(1,1,1)_12
m3_211.bhemanML = Arima(yellowstone_ts,order=c(2,1,1),seasonal=list(order=c(1,1,1), period=12),method = "ML")
coeftest(m3_211.bhemanML)
residual.analysis(model = m3_211.bhemanML)
```

```{r}
sort.score <- function(x, score = c("bic", "aic")){
  if (score == "aic"){
    x[with(x, order(AIC)),]
  } else if (score == "bic") {
    x[with(x, order(BIC)),]
  } else {
    warning('score = "x" only accepts valid arguments ("aic","bic")')
  }
}
```

```{r}
sort.score(AIC(m3_512.bhemanML, m3_112.bhemanML, m3_212.bhemanML, m3_113.bhemanML, m3_213.bhemanML, m3_111.bhemanML, m3_211.bhemanML), score = "aic")
```

```{r}
sort.score(BIC(m3_512.bhemanML, m3_112.bhemanML, m3_212.bhemanML, m3_113.bhemanML, m3_213.bhemanML, m3_111.bhemanML, m3_211.bhemanML), score = "bic")
```

```{r}
# Computing accuracy for each model
Sm3_512.bhemanML <- accuracy(m3_512.bhemanML)[, c("ME", "RMSE", "MAE", "MASE", "ACF1")]
Sm3_112.bhemanML <- accuracy(m3_112.bhemanML)[, c("ME", "RMSE", "MAE", "MASE", "ACF1")]
Sm3_212.bhemanML <- accuracy(m3_212.bhemanML)[, c("ME", "RMSE", "MAE", "MASE", "ACF1")]
Sm3_113.bhemanML <- accuracy(m3_113.bhemanML)[, c("ME", "RMSE", "MAE", "MASE", "ACF1")]
Sm3_213.bhemanML <- accuracy(m3_213.bhemanML)[, c("ME", "RMSE", "MAE", "MASE", "ACF1")]
Sm3_111.bhemanML <- accuracy(m3_111.bhemanML)[, c("ME", "RMSE", "MAE", "MASE", "ACF1")]
Sm3_211.bhemanML <- accuracy(m3_211.bhemanML)[, c("ME", "RMSE", "MAE", "MASE", "ACF1")]

# Combining into a data frame
df.Smodels <- data.frame(
  rbind(Sm3_512.bhemanML, Sm3_112.bhemanML, Sm3_212.bhemanML,  
        Sm3_113.bhemanML, Sm3_213.bhemanML, Sm3_111.bhemanML, Sm3_211.bhemanML)
)

# Renaming rows
rownames(df.Smodels) <- c(
  "SARIMA(5,1,2)x(1,1,1)[12]", "SARIMA(1,1,2)x(1,1,1)[12]", "SARIMA(2,1,2)x(1,1,1)[12]", 
  "SARIMA(1,1,3)x(1,1,1)[12]", "SARIMA(2,1,3)x(1,1,1)[12]", "SARIMA(1,1,1)x(1,1,1)[12]", "SARIMA(2,1,1)x(1,1,1)[12]"
)

# Displaying rounded table
round(df.Smodels, digits = 3)

```

```{r}
# SARIMA(1,1,3)x(1,1,1)_12
m3_113.bhemanML = Arima(yellowstone_ts,order=c(1,1,3),seasonal=list(order=c(1,1,1), period=12),method = "ML")
coeftest(m3_113.bhemanML)
residual.analysis(model = m3_113.bhemanML)
```

```{r}
m4_113.bhemanCSS = Arima(yellowstone_ts,order=c(1,1,3),seasonal=list(order=c(1,1,1), period=12),method = "CSS")
coeftest(m4_113.bhemanCSS)
residual.analysis(model = m4_113.bhemanCSS)
```

```{r}
# SARIMA(2,1,2)x(1,1,1)_12
m3_212.bhemanML = Arima(yellowstone_ts,order=c(2,1,2),seasonal=list(order=c(1,1,1), period=12),method = "ML")
coeftest(m3_212.bhemanML)
residual.analysis(model = m3_212.bhemanML)
```

```{r}
m4_212.bhemanCSS = Arima(yellowstone_ts,order=c(2,1,2),seasonal=list(order=c(1,1,1), period=12),method = "CSS")
coeftest(m4_212.bhemanCSS)
residual.analysis(model = m4_212.bhemanCSS)
```

```{r}
m4_212.bhemanCSSML = Arima(yellowstone_ts,order=c(2,1,2),seasonal=list(order=c(1,1,1), period=12),method = "CSS-ML")
coeftest(m4_212.bhemanCSSML)
residual.analysis(model = m4_212.bhemanCSSML)
```



```{r}
# Fitting the model
fit_112 <- Arima(
  yellowstone_ts,                 
  order    = c(1, 1, 2),         
  seasonal = list(order = c(1, 1, 1), period = 12)  
)
 
# 10-month forecast
fc_10 <- forecast(fit_112, h = 10)

# Plotting the forecast
autoplot(fc_10) +
  ggtitle("                  Fig: 40 Yellowstone monthly visits – 10-month SARIMA forecast") +
  ylab("Visitor count") +
  xlab("Year")
 
# Printing the numeric forecast table
print(fc_10)
```


